### ISSUE TITLE
Support ?.. for cascades

### ISSUE THREAD

**Issue by seaneagan** [gbracha/nullAwareOperators#7]
For example:

``` dart
maybeList()?..addAll(list)
```

**Comment by nex3** [comment]
This looks pretty noisy to me. On the other hand, since the idea behind `..` is to obviate the need to manually create fluent interfaces, limiting its capabilities relative to `.` may work against that.

**Comment by ghost** [comment]
Somewhere in you program, define:
class Antinull {
   noSuchMethod(x)=>null;
}
final AN=new Antinull();

Now, you can safely write (maybeList()??AN).addList(list)
:-)
Even more interesting to define another class (say, BlackHole) with noSuchMethod(x)=>this;
Then it becomes contagious. ((null??BH)+5)*15+20) returns BH
BTW, noSuchMethod, though very slow if you really start dealing with Invocation object (parameter of NoSuchMethod), is very fast if you don't. That is, invocation object is evaluated lazily, so if you don't touch it, there's no penalty

**Comment by gbracha** [comment]
It would be nice to have cascades work uniformly with this feature. On the other hand, we really want to keep this proposal dead simple.

**Comment by gbracha** [comment]
We aren't doing this.

**Comment by seaneagan** [comment]
Do you mean "we are never doing this" or "we are not doing this in this DEP" ?

**Comment by gbracha** [comment]
I meant it wasn't part of this DEP. But the text approved by TC52 allows for experimentation on th etopic, so we should be able to add it if no surprises come up.
